"""Added breed column

Revision ID: 539b64b3247b
Revises: 
Create Date: 2023-09-29 15:16:27.214301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539b64b3247b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puppies', schema=None) as batch_op:
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
